Updating HMTL/JS and adding React example
mercadopago/checkout-payment-sample pull request #14
Opened 2023-03-22 20:09 UTC by icaldana

**Updating full integration example for Checkout Pro due to the Wallet Brick changes** 

### Description
- Updated HTMLJS example
- Added ReactJS  example using the same UXto

### Imagens
![image](https://user-images.githubusercontent.com/30550706/223166435-18b2a8f8-200e-49d5-aee5-21907784c270.png)

2023-03-27 14:53 UTC, elvisjhonataoliveira requested changes

2023-03-27 14:53 UTC, elvisjhonataoliveira commented on client/reactjs/src/components/Payment.jsx
> +  const handleOnReady = () => {
Creio ser desnecessária essa função, uma vez que apenas utilizamos para fins de log.

2023-03-27 14:53 UTC, elvisjhonataoliveira commented on client/reactjs/src/components/Payment.jsx
> +        onReady={handleOnReady} />
Podemos remover a referência desse ponto também.

2023-03-27 14:53 UTC, elvisjhonataoliveira commented on client/reactjs/src/components/Checkout.jsx
> +      updatePrice();
Se não existir ainda um `preferenceId`, não vai falhar? Qual cenário queremos que execute esse `useEffect` ao invés de só executar o anterior que monitora o `prefereneId`.

2023-03-27 16:38 UTC, icaldana commented on client/reactjs/src/components/Checkout.jsx
> +      updatePrice();
Não falha, mas a lógica poderia sim ser revista.

2023-03-27 16:39 UTC, icaldana commented on client/reactjs/src/components/Checkout.jsx
> +    let quantity = document.getElementById("quantity").value || 1;
Essas melhorias, embora ótimas sugestões, não fugiriam demais da proposta do projeto?

2023-03-28 13:32 UTC, elvisjhonataoliveira approved these changes

2023-04-04 12:18 UTC, elvisjhonataoliveira approved these changes

2023-04-04 12:18 UTC, merged